---
- name: Add motd file
  become: true
  ansible.builtin.template:
    src: etc/motd.j2
    dest: /etc/motd
    backup: true
    mode: "0644"
    owner: root
    group: root

- name: Add issue and issue.net files
  become: true
  ansible.builtin.template:
    src: etc/issue.j2
    dest: "{{ item }}"
    backup: true
    mode: "0644"
    owner: root
    group: root
  with_items:
    - /etc/issue
    - /etc/issue.net
