---
- name: Install local facts
  ansible.builtin.import_tasks:
    file: facts.yml
  tags:
    - always

- name: Configure package manager
  ansible.builtin.import_tasks:
    file: packagemgmt.yml

- name: Configure systemd timesyncd
  ansible.builtin.import_tasks:
    file: timesyncd.yml
  when: manage_timesyncd

- name: Configure needrestart, install and remove various packages
  ansible.builtin.import_tasks:
    file: packages.yml

- name: Configure apport
  ansible.builtin.import_tasks:
    file: apport.yml

- name: Configure motdnews
  ansible.builtin.import_tasks:
    file: motdnews.yml

- name: Configure sudo
  ansible.builtin.import_tasks:
    file: sudo.yml

- name: Add issue message
  ansible.builtin.import_tasks:
    file: issue.yml
