---
- name: Install local facts
  ansible.builtin.include_tasks: facts.yml

- name: Configure local facts and install python dependencies
  ansible.builtin.include_tasks: pre.yml

- name: Configure package manager
  ansible.builtin.include_tasks: packagemgmt.yml

- name: Configure systemd timesyncd
  ansible.builtin.include_tasks: timesyncd.yml
  when: enable_timesyncd

- name: Configure needrestart, install and remove various packages
  ansible.builtin.include_tasks: packages.yml

- name: Configure apport
  ansible.builtin.include_tasks: apport.yml

- name: Configure motdnews
  ansible.builtin.include_tasks: motdnews.yml

- name: Configure sudo
  ansible.builtin.include_tasks: sudo.yml

- name: Add issue message
  ansible.builtin.include_tasks: issue.yml
