---
- name: Configure needrestart
  become: true
  block:
    - name: Pre register needrestart configuration directory
      ansible.builtin.stat:
        path: /etc/needrestart/conf.d
      register: needrestart_directory_created

    - name: Create needrestart directory
      ansible.builtin.file:
        path: /etc/needrestart/conf.d
        state: directory
        owner: root
        group: root
        mode: "0755"
        recurse: true
      when:
        - ("needrestart" in packages_installation)
        - not needrestart_directory_created.stat.exists

    - name: Stat needrestart configuration directory
      ansible.builtin.stat:
        path: /etc/needrestart/conf.d
      register: needrestart_directory

    - name: Get needrestart restart value
      ansible.builtin.command:
        cmd: grep -Rqo "$nrconf{restart} = 'l';" /etc/needrestart/conf.d/
      register: needrestart_restart_set
      when: needrestart_directory.stat.exists
      changed_when: false
      failed_when: needrestart_restart_set.rc > 1

    - name: Configure needrestart
      ansible.builtin.lineinfile:
        path: /etc/needrestart/conf.d/00-restart.conf
        line: $nrconf{restart} = 'l';
        create: true
        owner: root
        group: root
        mode: "0644"
      when:
        - needrestart_directory.stat.exists
        - needrestart_restart_set.rc != 0

- name: Package installation
  become: true
  ansible.builtin.apt:
    package: "{{ packages_installation }}"
    state: present
    install_recommends: false

- name: Ubuntu update-notifier-common package installation
  become: true
  ansible.builtin.apt:
    package: update-notifier-common
    state: present
    install_recommends: false

- name: Run apt purge
  become: true
  ansible.builtin.apt:
    package: "{{ packages_blocklist }}"
    state: absent
    purge: true
  register: apt_purge
  failed_when:
    - apt_purge is not success
    - not "No package" in apt_purge.msg

- name: Generic package removal
  become: true
  ansible.builtin.package:
    name: "{{ packages_blocklist }}"
    state: absent
  register: package_removal
  failed_when:
    - package_removal is not success
    - not "No package" in package_removal.msg

- name: VirtualBox guest packages installation
  become: true
  ansible.builtin.apt:
    package: "{{ packages }}"
    state: present
    install_recommends: false
  vars:
    packages:
      - virtualbox-guest-dkms
      - virtualbox-guest-utils
  register: virtualbox_packages
  when:
    - ansible_facts.virtualization_type == "VirtualBox"
  failed_when:
    - virtualbox_packages is not success
    - not "No package matching" in virtualbox_packages.msg

- name: VMWare package installation
  become: true
  ansible.builtin.package:
    name: open-vm-tools
    state: present
  when:
    - ansible_facts.virtualization_type == "VMware"

- name: QEMU package installation
  become: true
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present
  when:
    - ansible_facts.system_vendor == "QEMU"

- name: Install rng-tools
  become: true
  ansible.builtin.package:
    name: rng-tools
    state: present
  when:
    - "'rdrand' in ansible_facts.flags"

- name: Stat sysstat default
  become: true
  ansible.builtin.stat:
    path: /etc/default/sysstat
  register: default_sysstat

- name: Enable sysstat
  become: true
  ansible.builtin.lineinfile:
    regexp: ^ENABLED
    line: ENABLED="true"
    path: /etc/default/sysstat
    mode: "0644"
    state: present
    create: false
    backrefs: true
  when:
    - default_sysstat.stat.exists

- name: Remove unneeded Debian dependencies
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
