---
- name: Configure apt
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/98-hardening-ubuntu
    mode: "0644"
    state: present
    create: true
    line: "{{ item }}"
  with_items:
    - Acquire::AllowDowngradeToInsecureRepositories "false";
    - Acquire::AllowInsecureRepositories "false";
    - Acquire::http::AllowRedirect "false";
    - APT::Get::AllowUnauthenticated "false";
    - APT::Get::AutomaticRemove "true";
    - APT::Install-Recommends "false";
    - APT::Install-Suggests "false";
    - APT::Periodic::AutocleanInterval "7";
    - APT::Sandbox::Seccomp "1";
    - Unattended-Upgrade::Remove-Unused-Dependencies "true";
    - Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

- name: Run apt update and upgrade
  become: true
  block:
    - name: Run apt update
      ansible.builtin.apt:
        update_cache: true
      register: cache_updated
      changed_when: false
      until:
        - cache_updated is success

    - name: Run apt upgrade
      ansible.builtin.apt:
        upgrade: safe
      register: apt_upgrade_response
      changed_when:
        - "'0 upgraded, 0 newly installed, 0 to remove' not in apt_upgrade_response.stdout"
      until:
        - apt_upgrade_response is success
      when:
        - system_upgrade | bool
      notify:
        - Run apt-get clean
        - Run apt-get autoremove
