---
- name: Configure apt
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/98-hardening-ubuntu
    mode: "0644"
    state: present
    create: true
    line: "{{ item }}"
  with_items:
    - Acquire::AllowDowngradeToInsecureRepositories "false";
    - Acquire::AllowInsecureRepositories "false";
    - Acquire::http::AllowRedirect "false";
    - APT::Get::AllowUnauthenticated "false";
    - APT::Get::AutomaticRemove "true";
    - APT::Install-Recommends "false";
    - APT::Install-Suggests "false";
    - APT::Periodic::AutocleanInterval "7";
    - APT::Sandbox::Seccomp "1";
    - Unattended-Upgrade::Remove-Unused-Dependencies "true";
    - Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
  tags:
    - apt
    - M1045

- name: Run apt update
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 1800
  notify:
    - Run apt-get clean
    - Run apt-get autoremove
  tags:
    - apt

- name: Run apt upgrade
  become: true
  ansible.builtin.apt:
    upgrade: safe
  register: apt_upgrade_response
  changed_when: apt_upgrade_response.stdout.find('0 upgraded') == -1
  when: system_upgrade | bool
  tags:
    - apt
    - CIS-UBUNTU2004-1.9
    - D3-SU
    - M1051
