---
- name: Configure sudo
  become: true
  block:
    - name: Configure sudo use_pty
      become: true
      ansible.builtin.lineinfile:
        line: Defaults use_pty
        path: /etc/sudoers.d/011_use_pty
        mode: "0440"
        state: present
        create: true
        validate: visudo -cf %s

    - name: Configure sudo logfile
      ansible.builtin.lineinfile:
        line: Defaults logfile="/var/log/sudo.log"
        path: /etc/sudoers.d/012_logfile
        mode: "0440"
        state: present
        create: true
        validate: visudo -cf %s

    - name: Configure sudo disable pwfeedback
      ansible.builtin.lineinfile:
        line: Defaults !pwfeedback
        path: /etc/sudoers.d/013_pwfeedback
        mode: "0440"
        state: present
        create: true
        validate: visudo -cf %s

    - name: Configure sudo disable visiblepw
      ansible.builtin.lineinfile:
        line: Defaults !visiblepw
        path: /etc/sudoers.d/014_visiblepw
        mode: "0440"
        state: present
        create: true
        validate: visudo -cf %s

    - name: Remove inconsistently named sudoer file
      ansible.builtin.file:
        path: /etc/sudoers.d/15_timeout
        state: absent

    - name: Configure sudo passwd_timeout
      ansible.builtin.lineinfile:
        line: Defaults passwd_timeout=1
        path: /etc/sudoers.d/015_passwdtimeout
        mode: "0440"
        state: present
        create: true
        validate: visudo -cf %s

    - name: Configure sudo timestamp_timeout
      ansible.builtin.lineinfile:
        line: Defaults timestamp_timeout=5
        path: /etc/sudoers.d/016_timestamptimeout
        mode: "0440"
        state: present
        create: true
        validate: visudo -cf %s

    - name: Configure sudo timestamp_type
      ansible.builtin.lineinfile:
        line: Defaults timestamp_type=tty
        path: /etc/sudoers.d/017_timestamptype
        mode: "0440"
        state: present
        create: true
        validate: visudo -cf %s

    - name: Configure sudo user password for privilege escalation
      ansible.builtin.lineinfile:
        line: Defaults {{ item }}
        path: /etc/sudoers.d/018_userpassword
        mode: "0440"
        state: present
        create: true
        validate: visudo -cf %s
      with_items:
        - "!rootpw"
        - "!runaspw"
        - "!targetpw"

- name: Create su group sugroup
  become: true
  ansible.builtin.group:
    name: sugroup
    state: present

- name: Configure su group
  become: true
  ansible.builtin.lineinfile:
    line: auth required pam_wheel.so use_uid group=sugroup
    path: /etc/pam.d/su
    mode: "0644"
    state: present
    create: true
