on:
  schedule:
    - cron: "0 1 * * */3"
name: Ansible Lint - Scheduled

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@6cf7cb8d0343b8f0e123638bdeafe8e020dc5b80 # main
